language: rust
os: linux
dist: focal
rust:
  - stable
  - beta
  - nightly
env:
  global:
    - RUSTFLAGS='-F warnings'
    - RUST_BACKTRACE=full
stages:
  - Check
  - Test
jobs:
  include:
    - stage: Check
      name: Format
      install: cargo fmt --version || rustup component add rustfmt
      script: cargo fmt --all -- --check
    - stage: Check
      name: Clippy
      install: cargo clippy --version || rustup component add clippy
      script: cargo clippy -- --deny warnings
    - stage: Check
      name: Deny
      install: cargo deny --version || travis_retry cargo install cargo-deny --locked
      script: cargo deny check --hide-inclusion-graph --show-stats
    - stage: Test
      os: osx
    - stage: Test
      os: windows
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
